# will build a C++ programme
language: cpp

# define build matrix
matrix:
    include:
        # Ubuntu 16.04 Xenial Xerus
        - os: linux
          dist: xenial
          sudo: required
          compiler: gcc
          env:
              OS_DIST=LINUX_XENIAL
              GMX_VERSION=2016
        - os: linux
          dist: xenial
          sudo: required
          compiler: gcc
          env:
              OS_DIST=LINUX_XENIAL
              GMX_VERSION=2018
        # Ubuntu 18.04 Bionic Beaver
        - os: linux
          dist: bionic
          sudo: required
          compiler: gcc
          env:
              OS_DIST=LINUX_BIONIC
              GMX_VERSION=2016
        - os: linux
          dist: bionic
          sudo: required
          compiler: gcc
          env:
              OS_DIST=LINUX_BIONIC
              GMX_VERSION=2018
    allow_failures:
        - GMX_VERSION=2019      # known API break
        - OS_DIST=LINUX_BIONIC  # new Ubuntu LTS not tested
    fast_finish: true

# install dependencies
install:
    # install linear algebra dependencies
    - sudo apt-get install -y libblas-dev
    - sudo apt-get install -y libatlas-base-dev
    - sudo apt-get install -y libopenblas-dev
    - sudo apt-get install -y liblapacke-dev
    # install boost
    - sudo apt-get install -y libboost-all-dev
    # install GROMACS
    - wget https://ftp.gromacs.org/pub/gromacs/gromacs-${GMX_VERSION}.tar.gz
    - tar -xvzf gromacs-${GMX_VERSION}.tar.gz
    - cd gromacs-${GMX_VERSION}
    - mkdir build
    - cd build
    - cmake -DGMX_FFT_LIBRARY=fftpack ..
    - make -j 2
    - sudo make install
    - . /usr/local/gromacs/bin/GMXRC

# prepare build process
before_script:
    - mkdir ${TRAVIS_BUILD_DIR}/build
    - cd ${TRAVIS_BUILD_DIR}/build

# build and test
script:
    - cmake ..
    - make -j 2
    - make check
    - sudo make install
    - /usr/local/chap/bin/chap -h
